version: '3.8'

services:
  backend:
    hostname: backend
    container_name: backend
    restart: on-failure
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
